version: "3.7"

services:

  frontend:
    image: timetracker/frontend
    container_name: timetracker_frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:80

  backend:
    image: timetracker/backend
    container_name: timetracker_backend
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ./backend/timetracker.db:/app/timetracker.db
